#!/bin/sh

# replace repository specific placeholders in the markdown files
CosmiQ/.githooks/.replace_by_git_vars.py CosmiQ/binder/binder_readme_raw.md CosmiQ/binder/README.md

# Example:
# [mybinder](https://mybinder.org/v2/gh/{ repository.name }}/{{ current.branch }})
